### ISSUE TITLE
Official Docker image

### ISSUE THREAD

**Issue by Pingue** [brontide/aioedgeos#2]
Is there an official docker image for this repo?

I have created https://hub.docker.com/r/pingue/aioedgeos as an interim.

(Thanks for creating this, BTW - nice and easy Dockerfile!)

**Comment by ewarnke** [comment]
https://hub.docker.com/r/brontide/edge2influx

The aioedgeos is the parent library.

**Comment by Pingue** [comment]
Brilliant, thanks!
