### ISSUE TITLE
ARM Support

### ISSUE THREAD

**Issue by asmith04** [brontide/aioedgeos#3]
HI, 

Thank you for this its amazing. However, I was wondering if you would be able to or possibly plan a release for arm/arm64?

I cloned down your repo and built one but i get the following error when it runs:
`2020-12-14 16:10:01,618:WARNING:root: for export isn't a dict, would likely cause trouble in processing skipping`

**Comment by brontide** [comment]
The influx tool runs just fine on arm64, let me drop in my multiarch CI file and it should be running soon.

The error you are getting is because your Edge router does not have DPI enabled ( or sometimes on the first run it will spit that out ).

**Comment by asmith04** [comment]
I was just coming to withdraw / close this after discovering an article where you explained that. CPI is now on and its stopped reporting it.  

Thank you for coming back to me on it. 

Ace, i have both ARM and ARM64 I was just testing on my ARM device, which i got an error for so built the image for ARM Support. Assumed the error was something related to what I had done. 

Happy to close this now :)

**Comment by brontide** [comment]
Latest tag is built for amd64, arm, and arm64.
